parameters:
#    wearplay_user.example.class: Wearplay\UserBundle\Example

services:
#    wearplay_user.example:
#        class: %wearplay_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
