parameters:
#    wearplay_product.example.class: Wearplay\ProductBundle\Example

services:
#    wearplay_product.example:
#        class: %wearplay_product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
