parameters:
#    wearplay_brand.example.class: Wearplay\BrandBundle\Example

services:
#    wearplay_brand.example:
#        class: %wearplay_brand.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
